/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cedric' at '9/4/16 5:19 PM' with Gradle 3.0
 *
 * @author cedric, @date 9/4/16 5:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
